version: '3'
services:
  quarkus-app:
    container_name: quarkus-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
    volumes:
      - ./deploy/v1/quarkus_data:/path/in/container
    networks:
      - quarkus-network
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd 
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/v1/mysql_data:/var/lib/mysql
    networks:
      - quarkus-network
networks:
  quarkus-network:
    driver: bridge
volumes:
  mysql_data:
  quarkus_data:
